# Generated by Django 2.0.2 on 2018-12-04 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='body',
        ),
        migrations.RemoveField(
            model_name='product',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='product',
            name='votes_total',
        ),
    ]
